import {
  CalendarIcon,
  EnvelopeIcon,
  CalendarClockIcon,
  CombinedFormIcon,
  ClassicScheduleIcon,
  SimulationIcon,
  SimpleFormIcon,
} from "../shared/icons";

const EXPERIENCES = [
  {
    id: "simple-host",
    title: "Simple Host Form",
    pitchTitle: "Create a Gathering",
    description: "Create a gathering with minimal inputs — title, dates, duration, and quorum threshold.",
    pitchDescription: "The core host experience — set up a group event in under a minute.",
    app: "quorum",
    icon: SimpleFormIcon,
    status: "active",
    persona: "host",
    category: "demo",
    load: () => import("./scheduling/SimpleHostForm.jsx"),
  },
  {
    id: "host-scheduling",
    title: "Availability Sets Explorer",
    pitchTitle: "Explore: Event Types",
    description: "Feature exploration: multi-set date/time windows with location availability matching and calendar overlay.",
    pitchDescription: "Availability sets, recurring/limited series, co-hosts, and event images.",
    app: "quorum",
    icon: CalendarIcon,
    status: "active",
    persona: "host",
    category: "demo",
    isExploration: true,
    load: () => import("./scheduling/HostSchedulingForm.jsx"),
  },
  {
    id: "invitee-response",
    title: "Invitee Response",
    pitchTitle: "Respond to an Invite",
    description: "Respond to a gathering invite by ranking your top preferences and marking times you're unavailable.",
    pitchDescription: "Rank your preferred times and locations from available options.",
    app: "quorum",
    icon: EnvelopeIcon,
    status: "active",
    persona: "invitee",
    category: "demo",
    load: () => import("./scheduling/InviteeExperience.jsx"),
  },
  {
    id: "invitee-calendar",
    title: "Invitee Calendar View",
    pitchTitle: "Calendar Response",
    description: "Respond to a gathering invite using an interactive calendar that shows available days and lets you pick specific time slots.",
    pitchDescription: "Pick your availability using an interactive calendar overlay.",
    app: "quorum",
    icon: CalendarClockIcon,
    status: "active",
    persona: "invitee",
    category: "demo",
    load: () => import("./scheduling/InviteeCalendarExperience.jsx"),
  },
  {
    id: "host-combined",
    title: "Commute Buffer Explorer",
    pitchTitle: "Explore: Commute Buffers",
    description: "Feature exploration: commute-aware scheduling with buffer times, ideal time preferences, and single-step setup.",
    pitchDescription: "Commute-aware scheduling with buffer times, ideal time preferences, and single-step setup.",
    app: "quorum",
    icon: CombinedFormIcon,
    status: "active",
    persona: "host",
    category: "demo",
    isExploration: true,
    load: () => import("./scheduling/HostCombinedForm.jsx"),
  },
  {
    id: "host-classic",
    title: "Time Slot Explorer",
    pitchTitle: "Explore: Time Slots",
    description: "Feature exploration: classic scheduling with specific time slots, groupings, and preference ranking.",
    pitchDescription: "Classic scheduling with specific start times, groupings, and preference ranking.",
    app: "quorum",
    icon: ClassicScheduleIcon,
    status: "active",
    persona: "host",
    category: "demo",
    isExploration: true,
    load: () => import("./scheduling/HostClassicScheduling.jsx"),
  },
  {
    id: "s01-simulation",
    title: "S-01: Scenario Simulation",
    pitchTitle: "Community Planning Session",
    description: "End-to-end simulation of a single host, single gathering with 12 invitees — watch quorum reached in real time.",
    pitchDescription: "Watch a full scheduling scenario play out — from invites to quorum to confirmation.",
    app: "quorum",
    icon: SimulationIcon,
    status: "active",
    persona: null,
    category: "scenario",
    load: () => import("./scheduling/S01Simulation.jsx"),
  },
];

export const APPS = [
  {
    id: "quorum",
    name: "Quorum",
    tagline: "Smart group scheduling",
    description: "Organize gatherings with quorum-based confirmation, location matching, and overflow support.",
    icon: CalendarClockIcon,
    status: "active",
  },
  {
    id: "trellis",
    name: "Trellis",
    tagline: "Content discovery",
    description: "Surface and share interesting content with your community.",
    icon: null,
    status: "coming_soon",
  },
];

export default EXPERIENCES;
